FROM python:3.8-slim-buster

RUN apt-get -y update
RUN apt-get install -y libgl1-mesa-dev
RUN apt-get install -y libglib2.0-0 libsm6 libxrender1 libxext6

ADD requirements.txt .
RUN python -m pip install -r requirements.txt

